/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/H2rLQ6y0rHL
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Chivo } from 'next/font/google'

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { DropdownMenuTrigger, DropdownMenuItem, DropdownMenuContent, DropdownMenu } from "@/components/ui/dropdown-menu"
import { Input } from "@/components/ui/input"
import Image from "next/image"
import ContactPage from "../contact/contact"
import { Wave } from "../ui/wave/wave"



export function MainPage() {
  return (
    <div className="flex flex-col min-h-[100dvh] ">
      <header className="w-[90%] p-[15px] rounded-[5px] fixed top-[5%] left-1/2 transform -translate-x-1/2 -translate-y-1/2 opacity-90 z-10 px-4 lg:px-6 h-14 flex items-center bg-[#004D40] text-white">
        <Link className="flex items-center justify-center" href="#">
          <ServerIcon className="h-6 w-6" />
          <span className="ml-2 font-bold">Latikva</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6 items-center">
          <div className="lg:hidden">
            <DropdownMenu >
              <DropdownMenuTrigger asChild>
                <Button className="rounded-full" size="icon" variant="ghost">
                  <MenuIcon className="h-6 w-6" />
                  <span className="sr-only">Toggle navigation</span>
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end" className="w-64">
                <DropdownMenuItem>
                  <Link className="text-sm font-medium hover:underline underline-offset-4" href="#services">
                    Services
                  </Link>
                </DropdownMenuItem>
                <DropdownMenuItem>
                  <Link className="text-sm font-medium hover:underline underline-offset-4" href="#infrasctrucure">
                    Infrastructure
                  </Link>
                </DropdownMenuItem>
                <DropdownMenuItem>
                  <Link className="text-sm font-medium hover:underline underline-offset-4" href="#security">
                    Sécurité
                  </Link>
                </DropdownMenuItem>
             
                <DropdownMenuItem>
                  <Link className="text-sm font-medium hover:underline underline-offset-4" href="#contact">
                    Contact
                  </Link>
                </DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          </div>
          <div className="hidden lg:flex">
            <Link className="text-sm font-medium hover:underline underline-offset-4 mx-5" href="#services">
              Services
            </Link>
            <Link className="text-sm font-medium hover:underline underline-offset- mx-5" href="#infrastructure">
              Infrastructure
            </Link>
            <Link className="text-sm font-medium hover:underline underline-offset- mx-5" href="#security">
              Sécurité
            </Link>
        
            <Link className="text-sm font-medium hover:underline underline-offset- mx-5" href="#contact">
              Contact
            </Link>
          </div>
        </nav>
      </header>
      <main className="flex flex-col items-center justify-center ">
        <section className="flex w-full  md:py-24 lg:py-32 bg-[#004D40] text-white  justify-center pt-40 ">
          <div className="container px-4 md:px-6 space-y-4 md:space-y-6">
            <div className="max-w-3xl space-y-2">
              <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl">
                Alimenter l&apos;avenir des données
              </h1>
              <p className="text-gray-400 md:text-xl">
                Latikva est un fournisseur de centres de données de premier plan, offrant des solutions sécurisées et
                efficaces pour les entreprises de toutes tailles.
              </p>
            </div>
            <div className="flex flex-col sm:flex-row items-start gap-4">
              <Link
                className="inline-flex h-10 items-center justify-center rounded-md bg-[#26A69A] px-8 text-sm font-medium text-white shadow transition-colors hover:bg-[#FF6F00] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-blue-950 disabled:pointer-events-none disabled:opacity-50"
                href="#contact"
              >
                Contactez-nous
              </Link>
             
            </div>
          </div>
        </section>
    
        <section>
          <Wave />
        </section>
        <section>
     
        </section>

        <section className="flex w-full py-12 md:py-24 lg:py-32 justify-center " id="infrastructure">
          <div className="px-4 md:px-6 space-y-12">
            <div className="flex flex-col md:flex-row gap-5">
              <div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">
                  Infrastructure de centre de données de pointe
                </h2>
                <p className="mt-4 text-gray-500 md:text-xl">
                  Les centres de données de pointe de Latikva sont conçus pour offrir une fiabilité, une évolutivité et
                  des performances inégalées. Notre infrastructure avancée garantit que vos données critiques soient
                  toujours disponibles et sécurisées.
                </p>
                <div className="mt-6 flex flex-col gap-4">
                  <div className="flex items-start gap-4">
                    <CpuIcon className="h-6 w-6 text-[#004D40]" />
                    <div>
                      <h3 className="text-lg font-bold">Matériel haute performance</h3>
                      <p className="text-gray-500">
                        Nos centres de données sont équipés des derniers serveurs, stockages et équipements réseau haute
                        performance pour gérer vos charges de travail les plus exigeantes.
                      </p>
                    </div>
                  </div>
                  <div className="flex items-start gap-4">
                    <BoltIcon className="h-6 w-6 text-[#004D40]" />
                    <div>
                      <h3 className="text-lg font-bold">Redondance de l&apos;alimentation et du refroidissement</h3>
                      <p className="text-gray-500">
                        Les centres de données de Latikva disposent de systèmes d&apos;alimentation et de refroidissement
                        redondants pour garantir le fonctionnement de votre infrastructure même en cas de perturbation.
                      </p>
                    </div>
                  </div>
                  <div className="flex items-start gap-4">
                    <NetworkIcon className="h-6 w-6 text-[#004D40]" />
                    <div>
                      <h3 className="text-lg font-bold">Connectivité robuste</h3>
                      <p className="text-gray-500">
                        Nos centres de données sont connectés à plusieurs fournisseurs d&apos;accès Internet haut débit,
                        garantissant à vos applications et services un accès fiable et à faible latence.
                      </p>
                    </div>
                  </div>
                </div>
              </div>
              <Image
                alt="Data Center"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full"
                height="310"
                src="/infrastructure.jpeg"
                width="550"
              />
            </div>
          </div>
        </section>
        <section className="flex w-full py-12 md:py-24 lg:py-32 bg-[#004D40] text-white justify-center" id="security">
          <div className="container px-4 md:px-6 space-y-12">
            <div className="flex flex-col md:flex-row-reverse gap-5">
              <div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">Sécurité sans compromis</h2>
                <p className="mt-4 text-gray-400 md:text-xl">
                  Chez Latikva, la sécurité est notre priorité. Nos centres de données sont équipés des dernières
                  mesures de sécurité physiques et numériques pour protéger vos informations sensibles.
                </p>
                <div className="mt-6 flex flex-col gap-4">
                  <div className="flex items-start gap-4">
                    <LockIcon className="h-6 w-6 text-[#26A69A]" />
                    <div>
                      <h3 className="text-lg font-bold">Sécurité physique</h3>
                      <p className="text-gray-400">
                        Nos centres de données disposent d&apos;une sécurité sur site 24h/24, de contrôles d&apos;accès
                        biométriques et de systèmes de surveillance avancés pour protéger votre infrastructure.
                      </p>
                    </div>
                  </div>
                  <div className="flex items-start gap-4">
                    <ShieldIcon className="h-6 w-6 text-[#26A69A]" />
                    <div>
                      <h3 className="text-lg font-bold">Mesures de cybersécurité</h3>
                      <p className="text-gray-400">
                        Les centres de données de Latikva sont protégés par des pare-feu de pointe, des systèmes de
                        détection d&apos;intrusion et un chiffrement avancé pour prévenir les accès non autorisés et les
                        violations de données.
                      </p>
                    </div>
                  </div>
                  <div className="flex items-start gap-4">
                    <KeyIcon className="h-6 w-6 text-[#26A69A]" />
                    <div>
                      <h3 className="text-lg font-bold">Conformité et certifications</h3>
                      <p className="text-gray-400">
                        Nos centres de données sont conformes aux normes et réglementations du secteur, notamment HIPAA, PCI DSS et SSAE 18, garantissant les plus hauts niveaux de protection des données.
                      </p>
                    </div>
                  </div>
                </div>
              </div>
              <Image
                alt="Security"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full "
                height="310"
                src="/secutite.jpeg"
                width="550"
              />
            </div>
          </div>
        </section>
        <section className="flex w-full py-12 md:py-24 lg:py-32 justify-center ">
          <div className="container px-4 md:px-6 space-y-12">
            <div className="flex flex-col md:flex-row gap-5">
              <div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">
                  Solutions de centres de données durables
                </h2>
                <p className="mt-4 text-gray-500 md:text-xl">
                  Latikva s&apos;engage dans la durabilité environnementale. Nos centres de données sont conçus pour
                  minimiser la consommation d&apos;énergie et réduire notre empreinte carbone, assurant un avenir plus vert
                  pour notre planète.
                </p>
                <div className="mt-6 flex flex-col gap-4">
                  <div className="flex items-start gap-4">
                    <SunIcon className="h-6 w-6 text-[#004D40]" />
                    <div>
                      <h3 className="text-lg font-bold">Énergie renouvelable</h3>
                      <p className="text-gray-500">
                        Les centres de données de Latikva sont alimentés par des sources d&apos;énergie renouvelables, notamment solaire et éolienne, pour réduire notre impact environnemental.
                      </p>
                    </div>
                  </div>
                  <div className="flex items-start gap-4">
                    <LeafIcon className="h-6 w-6 text-[#004D40]" />
                    <div>
                      <h3 className="text-lg font-bold">Conception écoénergétique</h3>
                      <p className="text-gray-500">
                        Nos centres de données sont conçus avec des systèmes de refroidissement écoénergétiques, un éclairage LED et d&apos;autres technologies durables pour minimiser la consommation d&apos;énergie.
                      </p>
                    </div>
                  </div>
                  <div className="flex items-start gap-4">
                    <RecycleIcon className="h-6 w-6 text-[#004D40]" />
                    <div>
                      <h3 className="text-lg font-bold">Gestion responsable des déchets</h3>
                      <p className="text-gray-500">
                        Latikva a mis en place des programmes complets de recyclage et de gestion des déchets pour assurer l&apos;élimination responsable des équipements électroniques et autres matériaux.
                      </p>
                    </div>
                  </div>
                </div>
              </div>
              <Image
                alt="Sustainability"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full"
                height="310"
                src="/solutions.jpeg"
                width="550"
              />
            </div>
          </div>
        </section>
        <section className="flex w-full py-12 md:py-24 lg:py-32 bg-[#004D40] text-white justify-center" id="contact">
          <div className="container px-4 md:px-6 space-y-6 text-center">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">Contactez-nous</h2>
            <p className="max-w-[700px] mx-auto text-gray-200 md:text-xl">
              Vous avez une question ou vous êtes intéressé par nos services ? Remplissez le formulaire ci-dessous et
              l&apos;un de nos experts vous recontactera.
            </p>
            <ContactPage />
          </div>
        </section>
      </main>
      <footer className=" flex items-center flex-col md:flex-row py-8  text-white bg-[#004D40]">
          <div className=" mx-auto px-4 md:px-6 flex flex-col md:flex-column items-center justify-between">
          <p className="  mt-4 ">© 2024 LATKIVA.</p>
          <p className="  "> Tous droits réservés.</p>
          </div>
          <div className=" mx-auto px-4 md:px-6 flex flex-col md:flex-column items-center justify-between">
          <p className="  mt-4 ">4 RUE RENE RAZEL</p>
          <p className="   ">91400 SACLAY</p>
          <p className="  mt-4 ">contact@latikva.fr</p>

          <p className="  mt-4 ">TEL: 01 89 70 36 47</p>
          </div>
       
      </footer>
    </div>
  )
}

function BoltIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z" />
      <circle cx="12" cy="12" r="4" />
    </svg>
  )
}


function CpuIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="16" height="16" x="4" y="4" rx="2" />
      <rect width="6" height="6" x="9" y="9" rx="1" />
      <path d="M15 2v2" />
      <path d="M15 20v2" />
      <path d="M2 15h2" />
      <path d="M2 9h2" />
      <path d="M20 15h2" />
      <path d="M20 9h2" />
      <path d="M9 2v2" />
      <path d="M9 20v2" />
    </svg>
  )
}


function KeyIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m15.5 7.5 2.3 2.3a1 1 0 0 0 1.4 0l2.1-2.1a1 1 0 0 0 0-1.4L19 4" />
      <path d="m21 2-9.6 9.6" />
      <circle cx="7.5" cy="15.5" r="5.5" />
    </svg>
  )
}


function LeafIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M11 20A7 7 0 0 1 9.8 6.1C15.5 5 17 4.48 19 2c1 2 2 4.18 2 8 0 5.5-4.78 10-10 10Z" />
      <path d="M2 21c0-3 1.85-5.36 5.08-6C9.5 14.52 12 13 13 12" />
    </svg>
  )
}


function LockIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="11" x="3" y="11" rx="2" ry="2" />
      <path d="M7 11V7a5 5 0 0 1 10 0v4" />
    </svg>
  )
}


function MenuIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}


function NetworkIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect x="16" y="16" width="6" height="6" rx="1" />
      <rect x="2" y="16" width="6" height="6" rx="1" />
      <rect x="9" y="2" width="6" height="6" rx="1" />
      <path d="M5 16v-3a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v3" />
      <path d="M12 12V8" />
    </svg>
  )
}


function RecycleIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M7 19H4.815a1.83 1.83 0 0 1-1.57-.881 1.785 1.785 0 0 1-.004-1.784L7.196 9.5" />
      <path d="M11 19h8.203a1.83 1.83 0 0 0 1.556-.89 1.784 1.784 0 0 0 0-1.775l-1.226-2.12" />
      <path d="m14 16-3 3 3 3" />
      <path d="M8.293 13.596 7.196 9.5 3.1 10.598" />
      <path d="m9.344 5.811 1.093-1.892A1.83 1.83 0 0 1 11.985 3a1.784 1.784 0 0 1 1.546.888l3.943 6.843" />
      <path d="m13.378 9.633 4.096 1.098 1.097-4.096" />
    </svg>
  )
}


function ServerIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="8" x="2" y="2" rx="2" ry="2" />
      <rect width="20" height="8" x="2" y="14" rx="2" ry="2" />
      <line x1="6" x2="6.01" y1="6" y2="6" />
      <line x1="6" x2="6.01" y1="18" y2="18" />
    </svg>
  )
}


function ShieldIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z" />
    </svg>
  )
}


function SunIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="4" />
      <path d="M12 2v2" />
      <path d="M12 20v2" />
      <path d="m4.93 4.93 1.41 1.41" />
      <path d="m17.66 17.66 1.41 1.41" />
      <path d="M2 12h2" />
      <path d="M20 12h2" />
      <path d="m6.34 17.66-1.41 1.41" />
      <path d="m19.07 4.93-1.41 1.41" />
    </svg>
  )
}
